Builds out base template, adds page title mixin
RockefellerArchiveCenter/aquila pull request #19
Opened 2020-07-06 20:49 UTC by helrond

Builds out `base.html` with additional includes for head, navbar and scripts.
Adds Bootstrap files (CSS and JS) to static directory
Adds a PageTitleMixin to simplify process of adding page titles to views (used in templates in multiple places)

**NOTE:** This is branched from #13, so that should be merged first.

2020-07-07 14:40 UTC, bonniegee approved these changes

2020-07-07 16:50 UTC, HaSistrunk requested changes

2020-07-07 16:50 UTC, HaSistrunk commented on assign_rights/templates/base.html
> +        <!-- Content Header (Page header) -->
I think it makes sense to move the h1 into `<main>` wrapped in `<div>` instead of `<section>` elements.

2020-07-07 16:50 UTC, HaSistrunk commented on assign_rights/templates/navbar.html
> +  <nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-2" role="navigation" aria-label="{% trans 'navbar' %}">
```suggestion
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark mb-2" role="navigation">
```

2020-07-07 16:50 UTC, HaSistrunk commented on assign_rights/templates/users/login.html
> +        <input type="text" name="username" id="{{ form.username.id_for_label }}" class="form-control" placeholder="Username" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" /
Both inputs in the form need associated form labels where the "for" value matches the input id: `<label for="id_for_label">Username</label>`. The placeholder text is not necessary/not optimal. See https://webaim.org/techniques/forms/controls

2020-07-08 14:21 UTC, HaSistrunk approved these changes

2020-07-08 15:21 UTC, p-galligan approved these changes

2020-07-08 15:25 UTC, merged