Update Travis config
RockefellerArchiveCenter/aquila pull request #191
Opened 2021-09-16 14:47 UTC by bonniegee

Updates Travis config as part of CI maintenance. I was getting a bit tripped up by using `PORT` as a variable, since that variable is also used in deployment. Do I not need to worry about it since it will be overwritten?

The README will need to be updated, but I'll do that in a separate PR as I want to move this forward before finishing setting up deployment on production (and making these changes in pictor).

I know there is an open dependency PR but I decided not to include that fix here, since the most recent version of Django is still using sqlparse `0.4.1`.

2021-09-16 15:34 UTC, helrond requested changes
Cool this looks good! I like the addition of the APPLICATION_NAME variable, and am going to roll that into my changes to Zodiac.

Regarding the port - the environment variables you set in Travis CI are available here, so you could just target ${DJANGO_PORT}. Again, I'll update that in Zodiac.

Can you add an `after_script:` section to print out the coverage report? That helps us measure how good unit test coverage is. See [zodiac](https://github.com/RockefellerArchiveCenter/zodiac/blob/ci/.travis.yml#L18-L19)

Last, it is possible to update sqlparse - you'll need to delete the requirements.txt file and run `pip-compile`.

2021-09-16 15:41 UTC, bonniegee commented
> Regarding the port - the environment variables you set in Travis CI are available here, so you could just target $DJANGO_PORT. Again, I'll update that in Zodiac.

In the case of $DJANGO_PORT, we have that value as specific to each branch for this application, which would mean we would need to set it in this file for Travis to successfully run on other branches?

2021-09-16 18:42 UTC, helrond commented
> In the case of $DJANGO_PORT, we have that value as specific to each branch for this application, which would mean we would need to set it in this file for Travis to successfully run on other branches?

Yes, that's right - I would recommend just making that variable apply to all branches (which would mean deleting the two existing variables and re-adding).

2021-09-22 21:37 UTC, helrond requested changes
A couple of minor things.

2021-09-22 21:37 UTC, helrond commented on docker-compose.yml
> +      - "8009:8000"
```suggestion
      - "8009:8009"
```

2021-09-22 21:37 UTC, helrond commented on .travis.yml
>      - SERVICE_NAME: aquila-web
Two things: 
- we've called the `SERVICE_NAME` variable `CONTAINER` in other contexts and I'd prefer to be consistent. 
- I think it makes sense to use a `DJANGO_PORT` variable here, even though there's also a environment variable already defined in Travis for deployment. Getting these ports all aligned as variables is going to take some more thinking, but in the meantime it's useful to have that pulled out as a variable so we remember we have to deal with it.

2021-09-22 21:37 UTC, helrond commented on .travis.yml
> +  - ./wait-for-it.sh ${SERVICE_NAME}:8009 -- docker-compose exec ${SERVICE_NAME} pip install coverage pre-commit
Use a variable for the port number as described above.

2021-09-22 21:37 UTC, helrond commented on .travis.yml
>      on: &development
```suggestion
    on:
```

2021-09-22 22:31 UTC, helrond approved these changes

2021-09-23 15:46 UTC, HaSistrunk approved these changes

2021-09-23 20:23 UTC, p-galligan approved these changes

2021-09-24 11:59 UTC, merged