Implement RAC Style Library
RockefellerArchiveCenter/aquila pull request #303
Opened 2024-03-22 13:34 UTC by HaSistrunk

Fixes #298 

Implements the RAC Style Library.

- Removes Bootstrap styles and associated scripts
- Adds custom script for toggling mobile nav
- The manage rights and groupings forms are still using the bootstrap 4 crispy template pack, but I've added and edited the `checkbox_select_multiple.html` and `field_errors_block.html templates from that bootstrap4 template pack to add RAC Style Library classes for checkboxes and form errors.

Question:
- I removed the aria labels for the request and response info divs, because aria-label on divs is not universally supported by screenreaders, and it doesn't make sense to label those for screenreaders and not for everyone. However, I may have gone too far the other directions and made those labels into `<h2>` elements. Is that necessary? We should either remove all labels/headings, or include headings for all users.

Suggested updates to the Style Library:
- Add a `font-weight--bold` class
- Adjust `input__error` styles to have a width of 100% 
- H2 has padding below it that makes way too much space. This is because our original h2 from rockarch.org had a dotted border below it, and the padding is for that. Ideally, those padding styles would be part of the “heading—dotted-border" class in the style library, not the h2.
- Remove `select__label` and `select__control` classes from the Style Guide select component. Those aren't actually in the Style Library CSS.
- Revisit table styles to consider color contrast with links in tables, text alignment, and maybe some lines instead of just color for better visual separation of content. The tables look a little funky here.
- Consider making `card` styles more flexible. In the RAC Style Guide/Library, they were conceived to be a list of things where the card itself is clickable. We could expand these to be more flexible as containers of other kinds of content.

Unresolved issues:
- The bootstrap4 crispy template pack we are using for forms doesn't handle form errors in the best way for accessibility (the error is not programmatically connected to the related input with something like an aria-describedby, and there is no aria-invalid on the associated input). I got tired of messing with the forms, but this is something I should probably fix.

2024-03-22 13:39 UTC, HaSistrunk commented
Note: I did choose to use color variables in my local styles. I was thinking this would make maintenance easier if there were updates to the Style Library so that someone could quickly see what a color was in our Style Guide by name.

2024-03-25 21:35 UTC, helrond reviewed
I haven't gotten super into the weeds on the accessibility side of things, but from a general HTML/Django perspective this all makes sense to me (and this looks quite slick!). 

A couple of thoughts:
- It looks like you grabbed `rac_base.html` and `api.html` from the Argo repo, which makes sense. HOWEVER a couple of things: the endpoint that is available in the UI is a POST route, but there is no POST form, so it's basically a useless page. I'm divided on whether this page should just go away, or if it makes sense to keep it around but add that form back in...I'm not sure what the thinking was on having it in the UI in the first place but at this point the utility seems limited.
- If you _do_ end up keeping the API UI, we should remove the div with the Request Parameters header because that is specific to the RAC API and doesn't provide much info here. I don't hate the headers for the page sections as much as I thought I would, so definitely something to evaluate for Argo as well.

2024-03-25 21:36 UTC, helrond commented
Oh, and let me know if you have issues with figuring out how to associate the inputs and error messages. The data should be available to you in the templates.

2024-03-27 14:24 UTC, HaSistrunk commented
> I'm divided on whether this page should just go away, or if it makes sense to keep it around but add that form back in...I'm not sure what the thinking was on having it in the UI in the first place but at this point the utility seems limited.

Looking back at the issues and PRs in this repo re: the API, there isn't a lot to go on, but it seemed like we just wanted to make the [endpoints browseable](https://github.com/RockefellerArchiveCenter/aquila/issues/148). Now that aquila is up and running, if we aren't using that I'm happy to get rid of it, but I haven't worked with aquila so I don't have a lot of info to make that call.

2024-04-02 19:18 UTC, HaSistrunk commented
> Oh, and let me know if you have issues with figuring out how to associate the inputs and error messages. The data should be available to you in the templates.

Ok, so I tried to edit templates to do this, but I'm struggling to find a way to make it work. Basically, the error message divs already have associated ids, so I was trying to add an `aria-describedby` to the form input that is the same as that id. I feel like there might be an easier way to do it in views.py, but I can't figure it out. I also looked at using [crispy-boostrap5](https://github.com/django-crispy-forms/crispy-bootstrap5) instead, but there were no improvements in version 5 for form validation accessibility. [Django 5 core has made progress on this](https://www.djangoproject.com/weblog/2024/feb/10/django-accessibility-in-2023-and-beyond/), though.

2024-04-05 14:44 UTC, HaSistrunk commented
Upon further consideration, it may make sense to get rid of crispy forms altogether. There's a lot to extract and replace from crispy forms here, though.

2024-04-16 20:35 UTC, HaSistrunk commented
Update: I've removed crispy forms, but am struggling to adjust the RightsShellUpdateForm to render correctly.

2024-04-29 12:53 UTC, HaSistrunk commented
Final changes here and this is ready for review:
- I removed the browseable API because the team determined it wasn't used or useful.
- I decided to keep crispy forms, because the Layout feature that we are using in forms.py to create a Right Shell Common Layout is incredibly useful. Our form error message patterns may need some accessibility work in the future, but there are some variations in approach that may be useful to look at together across sites and in the Style Guide.

2024-04-29 17:26 UTC, p-galligan approved these changes

2024-04-29 17:28 UTC, helrond requested changes
Just one question (which, if there's a good reason for, should just be documented as a code comment).

2024-04-29 17:28 UTC, helrond commented on assign_rights/forms.py
> +        self.helper.disable_csrf = True
This seems...unexpected. Any insight into why this is disabled?

2024-04-29 17:47 UTC, HaSistrunk commented on assign_rights/forms.py
> +        self.helper.disable_csrf = True
It was added in PR #92 , but no specific explanation there or in other PRs/issues that I can find. And I see in the template that we have added {% csrf_token %} in the [rights/manage.html form](https://github.com/RockefellerArchiveCenter/aquila/blob/55f2311267346732badfe51a5bdd0c36c12737a4/assign_rights/templates/rights/manage.html#L9), so that conflicts (but the disable csrf is taking precedence here with the crispy form I think). I can't figure out why we would want that, so my inclination is to remove this line in forms.py unless you can recall a reason?

2024-04-29 18:13 UTC, helrond commented on assign_rights/forms.py
> +        self.helper.disable_csrf = True
I can't recall a reason - I guess just make sure the form is still functional after you remove it?

2024-04-30 14:30 UTC, helrond approved these changes

2024-04-30 14:43 UTC, merged